name: Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: secretpass
          POSTGRES_USER: chartdb
          POSTGRES_DB: chartdb-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        
    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Migrate PG
      run: |
        cd app
        pip install -e yandex-pgmigrate
        python -m yandex-pgmigrate migrate -c 'host=localhost port=5432 dbname=chartdb user=chartdb password=secretpass' -d . -t latest -v -a afterAll:./migrations/grants
    

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24.x'

    - name: Setup dependencies
      run: |
        cd app
        go mod download

    - name: Run tests
      run: |
        cd app
        go test -v ./...


  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
        docker build . --file ./deploy/Dockerfile --tag chartdb_back:latest

    - name: Set version timestamp
      run: echo "VERSION=$(date +%s)" >> $GITHUB_ENV
      
    - name: Tag image
      run: |
        docker tag chartdb_back:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/chartdb_back:latest
        docker tag chartdb_back:latest cr.yandex/${{ secrets.YC_REGISTRY_ID }}/chartdb_back:${{ env.VERSION }}

    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v3
      with:
        yc-sa-json-credentials: ${{ secrets.YC_KEY }}

    - name: Push image
      run: |
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/chartdb_back:latest
        docker push cr.yandex/${{ secrets.YC_REGISTRY_ID }}/chartdb_back:${{ env.VERSION }}
      
